// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
)

type Message struct {
	ID            uuid.UUID
	RoomID        uuid.UUID
	ReactionCount int64
	Answered      bool
	Message       string
}

type Room struct {
	ID    uuid.UUID
	Theme string
}
